/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio_8_5;

/**
 *
 * @author daniel
 */
import java.util.*;

import javax.swing.*;

import java.awt.*;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;

public class VentanaIngreso extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaIngreso.class.getName());

    /**
     * Creates new form VentanaIngreso
     */

    private Hotel hotel;
    private int numero_habitacionReservada;
    private Date fecha_inicial;
    private Container contenedor;
    private Habitacion habitacion_reservada;

    public VentanaIngreso(Hotel hotel, int numero_habitacionReservada) {
        this.hotel = hotel;
        this.numero_habitacionReservada = numero_habitacionReservada;
        initComponents();

        setLocationRelativeTo(null);
        setResizable(false);
        contenedor = getContentPane();
        contenedor.setLayout(new GridBagLayout());
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.insets = new Insets(3, 3, 3, 3);
        label_numeroHabitacion.setText("Habitación: " + numero_habitacionReservada);
        constraints.gridx = 0;
        constraints.gridy = 0;
        contenedor.add(label_numeroHabitacion, constraints);
        constraints.gridx = 0;
        constraints.gridy = 1;
        contenedor.add(label_fecha, constraints);
        constraints.gridx = 1;
        constraints.gridy = 1;
        contenedor.add(campo_fecha, constraints);
        constraints.gridx = 0;
        constraints.gridy = 2;
        contenedor.add(label_huesped, constraints);
        constraints.gridx = 0;
        constraints.gridy = 3;
        contenedor.add(label_nombre, constraints);
        constraints.gridx = 1;
        constraints.gridy = 3;
        contenedor.add(campo_nombre, constraints);
        constraints.gridx = 0;
        constraints.gridy = 4;
        contenedor.add(label_apellidos, constraints);
        constraints.gridx = 1;
        constraints.gridy = 4;
        contenedor.add(campo_apellidos, constraints);
        constraints.gridx = 0;
        constraints.gridy = 5;
        contenedor.add(label_identificacion, constraints);
        constraints.gridx = 1;
        constraints.gridy = 5;
        contenedor.add(campo_identificacion, constraints);
        constraints.gridx = 0;
        constraints.gridy = 6;
        contenedor.add(boton_aceptar, constraints);
        boton_aceptar.addActionListener((ActionListener) this);
        constraints.gridx = 1;
        constraints.gridy = 6;
        contenedor.add(boton_cancelar, constraints);
        boton_cancelar.addActionListener((ActionListener) this);
        

    }

    private VentanaIngreso() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_numeroHabitacion = new javax.swing.JLabel();
        label_fecha = new javax.swing.JLabel();
        label_huesped = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        label_apellidos = new javax.swing.JLabel();
        label_identificacion = new javax.swing.JLabel();
        campo_fecha = new javax.swing.JTextField();
        boton_aceptar = new javax.swing.JButton();
        boton_cancelar = new javax.swing.JButton();
        campo_nombre = new javax.swing.JTextField();
        campo_apellidos = new javax.swing.JTextField();
        campo_identificacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso");

        label_numeroHabitacion.setText("Habitación: 1");

        label_fecha.setText("Fecha (aaaa/mm/dd)");

        label_huesped.setText("Huésped");

        label_nombre.setText("Nombre");

        label_apellidos.setText("Apellidos");

        label_identificacion.setText("Identificación");

        boton_aceptar.setText("Aceptar");
        boton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aceptarActionPerformed(evt);
            }
        });

        boton_cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_numeroHabitacion)
                            .addComponent(label_huesped)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nombre)
                                    .addComponent(label_apellidos)
                                    .addComponent(label_identificacion)
                                    .addComponent(label_fecha))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(boton_aceptar)
                        .addGap(38, 38, 38)
                        .addComponent(boton_cancelar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label_numeroHabitacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_fecha)
                    .addComponent(campo_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_huesped)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nombre)
                    .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_apellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_identificacion))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_aceptar)
                    .addComponent(boton_cancelar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aceptarActionPerformed
        // TODO add your handling code here:
        int posicion = -1;
        for (int counter = 0; counter < hotel.lista_habitaciones.size(); counter++){
            Habitacion habitacion_actual = hotel.lista_habitaciones.elementAt(counter);
            if (habitacion_actual.getNumeroHabitacion() == this.numero_habitacionReservada){
                try{
                    posicion = counter;
                    String fechaIngresada = campo_fecha.getText();
                    SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
                    Date fecha = formato.parse(fechaIngresada);

                    Huesped huesped = new Huesped(campo_nombre.getText(), campo_apellidos.getText(), Integer.parseInt(campo_identificacion.getText()));
                    habitacion_actual.setHuesped(huesped);
                    habitacion_actual.setDisponible(false);
                    habitacion_reservada = habitacion_actual;
                    hotel.lista_habitaciones.set(posicion, habitacion_actual);
                    JOptionPane.showMessageDialog(this, "El huesped ha sido registrado exitosamente.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    setVisible(false);
                    break;
                }catch (ParseException parse_exception){
                    JOptionPane.showMessageDialog(this, "Error en el formato de la fecha. Use aaaa/mm/dd.", "Error", JOptionPane.ERROR_MESSAGE);
                }catch (Exception exception){
                    JOptionPane.showMessageDialog(this, "Campo nulo o error en formato de número", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }        
    }//GEN-LAST:event_boton_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaIngreso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_aceptar;
    private javax.swing.JButton boton_cancelar;
    private javax.swing.JTextField campo_apellidos;
    private javax.swing.JTextField campo_fecha;
    private javax.swing.JTextField campo_identificacion;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JLabel label_apellidos;
    private javax.swing.JLabel label_fecha;
    private javax.swing.JLabel label_huesped;
    private javax.swing.JLabel label_identificacion;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_numeroHabitacion;
    // End of variables declaration//GEN-END:variables
}
