/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio_8_5;

import java.awt.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;

/**
 *
 * @author daniel
 */
import java.util.*;

import javax.swing.JOptionPane;

public class VentanaSalida extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaSalida.class.getName());

    /**
     * Creates new form VentanaSalida
     */

    private Container contenedor;
    private Hotel hotel;
    private int numero_habitacion;
    private int posicion_habitacion;
    private Habitacion habitacion_ocupada;

    public VentanaSalida(Hotel hotel, int numero_habitacion) {
        this.hotel = hotel;
        this.numero_habitacion = numero_habitacion;
        initComponents();
        setLocationRelativeTo(null);
        contenedor = getContentPane();
        contenedor.setLayout(new GridBagLayout());
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.insets = new Insets(3, 3, 3, 3);
        label_numeroHabitacion.setText("Habitación: " + numero_habitacion);
        constraints.gridx = 0;
        constraints.gridy = 0;
        contenedor.add(label_numeroHabitacion, constraints);
        String fecha_ingreso = hotel.buscarFechaIngresoHabitacion(numero_habitacion);
        label_fechaIngreso.setText("Fecha de ingreso: " + fecha_ingreso);
        constraints.gridx = 0;
        constraints.gridy = 1;
        contenedor.add(label_fechaIngreso, constraints);
        constraints.gridx = 0;
        constraints.gridy = 2;
        contenedor.add(label_fechaSalida, constraints);
        constraints.gridx = 0;
        constraints.gridy = 3;
        contenedor.add(campo_fechaSalida, constraints);
        constraints.gridx = 0;
        constraints.gridy = 4;
        contenedor.add(boton_calcular, constraints);
        constraints.gridx = 0;
        constraints.gridy = 5;
        contenedor.add(label_cantidadDias, constraints);
        constraints.gridx = 0;
        constraints.gridy = 6;
        contenedor.add(label_valorTotal, constraints);
        constraints.gridx = 0;
        constraints.gridy = 7;
        contenedor.add(boton_registrarSalida, constraints);
        boton_registrarSalida.setEnabled(false);
    }

    private VentanaSalida() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_numeroHabitacion = new javax.swing.JLabel();
        label_fechaIngreso = new javax.swing.JLabel();
        label_fechaSalida = new javax.swing.JLabel();
        label_cantidadDias = new javax.swing.JLabel();
        label_valorTotal = new javax.swing.JLabel();
        campo_fechaSalida = new javax.swing.JTextField();
        boton_calcular = new javax.swing.JButton();
        boton_registrarSalida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Salida de huésped");
        setResizable(false);

        label_numeroHabitacion.setText("Habitación:");

        label_fechaIngreso.setText("Fecha de ingreso: ");

        label_fechaSalida.setText("Fecha de salida (aaaa-mm-dd):");

        label_cantidadDias.setText("Días de hospedaje: ");

        label_valorTotal.setText("Total: $");

        boton_calcular.setText("Calcular");
        boton_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_calcularActionPerformed(evt);
            }
        });

        boton_registrarSalida.setText("Registrar salida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_numeroHabitacion)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boton_calcular)
                        .addGap(139, 139, 139))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(campo_fechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_valorTotal)
                            .addComponent(label_cantidadDias)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(boton_registrarSalida)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_fechaIngreso)
                    .addComponent(label_fechaSalida))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label_numeroHabitacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_fechaIngreso)
                .addGap(12, 12, 12)
                .addComponent(label_fechaSalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(campo_fechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton_calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_cantidadDias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_valorTotal)
                .addGap(34, 34, 34)
                .addComponent(boton_registrarSalida)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_calcularActionPerformed
        // TODO add your handling code here:
        String fecha_salida = campo_fechaSalida.getText();
        String fecha_ingreso = hotel.buscarFechaIngresoHabitacion(numero_habitacion);
        for (int counter = 0; counter < hotel.lista_habitaciones.size(); counter++) {
            habitacion_ocupada = (Habitacion) hotel.lista_habitaciones.elementAt(counter);
            if (habitacion_ocupada.getNumeroHabitacion() == this.numero_habitacion) {
                try{
                    posicion_habitacion = counter;
                    SimpleDateFormat formato_fecha = new SimpleDateFormat("yyyy-MM-dd");
                    Date fecha_salidaDate = formato_fecha.parse(fecha_salida);
                    habitacion_ocupada.getHuesped().setFecha_salida(fecha_salidaDate);
                    Date fecha_ingresoDate = habitacion_ocupada.getHuesped().getFecha_ingreso();
                    if (fecha_ingresoDate.compareTo(fecha_salidaDate) < 0){
                        int dias_hospedaje = habitacion_ocupada.getHuesped().diasAlojamiento();
                        label_cantidadDias.setText("Días de hospedaje: " + dias_hospedaje);
                        double valor_total = dias_hospedaje * habitacion_ocupada.getPrecioNoche();
                        label_valorTotal.setText("Total: $" + valor_total);
                        boton_registrarSalida.setEnabled(true);
                    }else{
                        JOptionPane.showMessageDialog(this, "La fecha de salida es anterior a la de ingreso.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }catch (ParseException parseException){
                    JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Use aaaa-mm-dd.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_boton_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaSalida().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_calcular;
    private javax.swing.JButton boton_registrarSalida;
    private javax.swing.JTextField campo_fechaSalida;
    private javax.swing.JLabel label_cantidadDias;
    private javax.swing.JLabel label_fechaIngreso;
    private javax.swing.JLabel label_fechaSalida;
    private javax.swing.JLabel label_numeroHabitacion;
    private javax.swing.JLabel label_valorTotal;
    // End of variables declaration//GEN-END:variables
}
