/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio_8_5;

/**
 *
 * @author daniel
 */

import java.awt.*;

import javax.swing.JOptionPane;

public class VentanaHabitaciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaHabitaciones.class.getName());

    /**
     * Creates new form VentanaHabitaciones
     */
    private Container contenedor;
    private Hotel hotel;

    public VentanaHabitaciones(Hotel hotel) {
        this.hotel = hotel;
        initComponents();
        contenedor = getContentPane();
        contenedor.setLayout(null);

        Habitacion habitacion_actual;
        for (int counter = 0; counter < 10; counter++) {
            habitacion_actual = (Habitacion) hotel.lista_habitaciones.elementAt(counter);
            String disponibilidad;
            if (!habitacion_actual.getDisponible()){
                disponibilidad = "No disponible";
            } else {
                disponibilidad = "Disponible";
            }
            switch (counter) {
                case 0 -> label_disponibilidad1.setText(disponibilidad);
                case 1 -> label_disponibilidad2.setText(disponibilidad);
                case 2 -> label_disponibilidad3.setText(disponibilidad);
                case 3 -> label_disponibilidad4.setText(disponibilidad);
                case 4 -> label_disponibilidad5.setText(disponibilidad);
                case 5 -> label_disponibilidad6.setText(disponibilidad);
                case 6 -> label_disponibilidad7.setText(disponibilidad);
                case 7 -> label_disponibilidad8.setText(disponibilidad);
                case 8 -> label_disponibilidad9.setText(disponibilidad);
                case 9 -> label_disponibilidad10.setText(disponibilidad);
            }
        }

        contenedor.add(label_habitacion1);
        contenedor.add(label_disponibilidad1);
        contenedor.add(label_habitacion2);
        contenedor.add(label_disponibilidad2);
        contenedor.add(label_habitacion3);
        contenedor.add(label_disponibilidad3);
        contenedor.add(label_habitacion4);
        contenedor.add(label_disponibilidad4);
        contenedor.add(label_habitacion5);
        contenedor.add(label_disponibilidad5);
        contenedor.add(label_habitacion6);
        contenedor.add(label_disponibilidad6);
        contenedor.add(label_habitacion7);
        contenedor.add(label_disponibilidad7);
        contenedor.add(label_habitacion8);
        contenedor.add(label_disponibilidad8);
        contenedor.add(label_habitacion9);
        contenedor.add(label_disponibilidad9);
        contenedor.add(label_habitacion10);
        contenedor.add(label_disponibilidad10);
        contenedor.add(label_habitacionRequerida);
        contenedor.add(spinner_habitacionRequerida);
        contenedor.add(boton_aceptar);

    }

    private VentanaHabitaciones() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_habitacion1 = new javax.swing.JLabel();
        label_disponibilidad1 = new javax.swing.JLabel();
        label_habitacion2 = new javax.swing.JLabel();
        label_habitacion3 = new javax.swing.JLabel();
        label_habitacion4 = new javax.swing.JLabel();
        label_disponibilidad4 = new javax.swing.JLabel();
        label_habitacion5 = new javax.swing.JLabel();
        label_disponibilidad5 = new javax.swing.JLabel();
        label_habitacion6 = new javax.swing.JLabel();
        label_disponibilidad6 = new javax.swing.JLabel();
        label_habitacion7 = new javax.swing.JLabel();
        label_disponibilidad7 = new javax.swing.JLabel();
        label_disponibilidad2 = new javax.swing.JLabel();
        label_disponibilidad3 = new javax.swing.JLabel();
        label_habitacion8 = new javax.swing.JLabel();
        label_disponibilidad8 = new javax.swing.JLabel();
        label_habitacion9 = new javax.swing.JLabel();
        label_disponibilidad9 = new javax.swing.JLabel();
        label_habitacion10 = new javax.swing.JLabel();
        label_disponibilidad10 = new javax.swing.JLabel();
        label_habitacionRequerida = new javax.swing.JLabel();
        spinner_habitacionRequerida = new javax.swing.JSpinner();
        boton_aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Habitaciones");
        setResizable(false);

        label_habitacion1.setText("Habitación 1");

        label_disponibilidad1.setText("Disponible");

        label_habitacion2.setText("Habitación 2");

        label_habitacion3.setText("Habitación 3");

        label_habitacion4.setText("Habitación 4");

        label_disponibilidad4.setText("Disponible");

        label_habitacion5.setText("Habitación 5");

        label_disponibilidad5.setText("Disponible");

        label_habitacion6.setText("Habitación 6");

        label_disponibilidad6.setText("Disponible");

        label_habitacion7.setText("Habitación 7");

        label_disponibilidad7.setText("Disponible");

        label_disponibilidad2.setText("Disponible");

        label_disponibilidad3.setText("Disponible");

        label_habitacion8.setText("Habitación 8");

        label_disponibilidad8.setText("Disponible");

        label_habitacion9.setText("Habitación 9");

        label_disponibilidad9.setText("Disponible");

        label_habitacion10.setText("Habitación 10");

        label_disponibilidad10.setText("Disponible");

        label_habitacionRequerida.setText("Habitación a reservar:");

        spinner_habitacionRequerida.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        boton_aceptar.setText("Aceptar");
        boton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_habitacion1)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_disponibilidad1)
                                .addGap(102, 102, 102)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_habitacion6)
                            .addComponent(label_disponibilidad6))
                        .addGap(102, 102, 102)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_habitacion7)
                    .addComponent(label_habitacion2)
                    .addComponent(label_disponibilidad2)
                    .addComponent(label_disponibilidad7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_disponibilidad3)
                    .addComponent(label_habitacion3)
                    .addComponent(label_habitacion8)
                    .addComponent(label_disponibilidad8))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_disponibilidad4)
                    .addComponent(label_habitacion4)
                    .addComponent(label_habitacion9)
                    .addComponent(label_disponibilidad9))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_habitacion5)
                    .addComponent(label_disponibilidad5)
                    .addComponent(label_habitacion10)
                    .addComponent(label_disponibilidad10))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(label_habitacionRequerida)
                .addGap(18, 18, 18)
                .addComponent(spinner_habitacionRequerida, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(boton_aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_habitacion3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_disponibilidad3)
                        .addGap(40, 40, 40)
                        .addComponent(label_habitacion8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_disponibilidad8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_habitacion4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_disponibilidad4)
                        .addGap(40, 40, 40)
                        .addComponent(label_habitacion9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_disponibilidad9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_habitacion1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_disponibilidad1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_habitacion5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_disponibilidad5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_habitacion2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_disponibilidad2)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_habitacion6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_disponibilidad6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_habitacion7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_disponibilidad7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_habitacion10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_disponibilidad10)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_habitacionRequerida)
                    .addComponent(spinner_habitacionRequerida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_aceptar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aceptarActionPerformed
        // TODO add your handling code here:
        int habitacion_requerida = (int) spinner_habitacionRequerida.getValue();

        if (!hotel.buscarHabitacionOcupada(habitacion_requerida)){
            VentanaIngreso ventanaIngreso = new VentanaIngreso(hotel, habitacion_requerida);
            setVisible(false);
            ventanaIngreso.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "La habitación " + habitacion_requerida + " no está disponible.", "Mensaje", JOptionPane.INFORMATION_MESSAGE, null);
        }
        
    }//GEN-LAST:event_boton_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaHabitaciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_aceptar;
    private javax.swing.JLabel label_disponibilidad1;
    private javax.swing.JLabel label_disponibilidad10;
    private javax.swing.JLabel label_disponibilidad2;
    private javax.swing.JLabel label_disponibilidad3;
    private javax.swing.JLabel label_disponibilidad4;
    private javax.swing.JLabel label_disponibilidad5;
    private javax.swing.JLabel label_disponibilidad6;
    private javax.swing.JLabel label_disponibilidad7;
    private javax.swing.JLabel label_disponibilidad8;
    private javax.swing.JLabel label_disponibilidad9;
    private javax.swing.JLabel label_habitacion1;
    private javax.swing.JLabel label_habitacion10;
    private javax.swing.JLabel label_habitacion2;
    private javax.swing.JLabel label_habitacion3;
    private javax.swing.JLabel label_habitacion4;
    private javax.swing.JLabel label_habitacion5;
    private javax.swing.JLabel label_habitacion6;
    private javax.swing.JLabel label_habitacion7;
    private javax.swing.JLabel label_habitacion8;
    private javax.swing.JLabel label_habitacion9;
    private javax.swing.JLabel label_habitacionRequerida;
    private javax.swing.JSpinner spinner_habitacionRequerida;
    // End of variables declaration//GEN-END:variables
}
