/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio8_2;

/**
 *
 * @author daniel
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nota1 = new javax.swing.JLabel();
        label_nota2 = new javax.swing.JLabel();
        label_nota4 = new javax.swing.JLabel();
        label_nota3 = new javax.swing.JLabel();
        label_nota5 = new javax.swing.JLabel();
        campo_nota1 = new javax.swing.JTextField();
        campo_nota2 = new javax.swing.JTextField();
        campo_nota5 = new javax.swing.JTextField();
        campo_nota4 = new javax.swing.JTextField();
        campo_nota3 = new javax.swing.JTextField();
        boton_calcular = new javax.swing.JButton();
        boton_limpiar = new javax.swing.JButton();
        label_promedio = new javax.swing.JLabel();
        label_maxima = new javax.swing.JLabel();
        label_desviacion = new javax.swing.JLabel();
        label_minima = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notas");

        label_nota1.setText("Nota 1:");

        label_nota2.setText("Nota 2:");

        label_nota4.setText("Nota 4:");

        label_nota3.setText("Nota 3:");

        label_nota5.setText("Nota 5:");

        boton_calcular.setText("Calcular");
        boton_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_calcularActionPerformed(evt);
            }
        });

        boton_limpiar.setText("Limpiar");
        boton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarActionPerformed(evt);
            }
        });

        label_promedio.setText("Promedio: ");

        label_maxima.setText("Nota máxima: ");

        label_desviacion.setText("Desviación estándar:");

        label_minima.setText("Nota mínima:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_minima)
                            .addComponent(label_desviacion)
                            .addComponent(label_maxima)
                            .addComponent(label_promedio))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_nota5)
                                    .addComponent(label_nota2)
                                    .addComponent(label_nota1)
                                    .addComponent(label_nota3)
                                    .addComponent(label_nota4))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_nota1)
                                    .addComponent(campo_nota2)
                                    .addComponent(campo_nota3)
                                    .addComponent(campo_nota4)
                                    .addComponent(campo_nota5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(boton_calcular)
                                .addGap(28, 28, 28)
                                .addComponent(boton_limpiar)))
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nota1)
                    .addComponent(campo_nota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nota2)
                    .addComponent(campo_nota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nota3)
                    .addComponent(campo_nota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nota4)
                    .addComponent(campo_nota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nota5)
                    .addComponent(campo_nota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_calcular)
                    .addComponent(boton_limpiar))
                .addGap(18, 18, 18)
                .addComponent(label_promedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_desviacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_maxima)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_minima)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_calcularActionPerformed
        // TODO add your handling code here:
        
        Notas notas = new Notas(); // crea un objeto de la clase Notas
        notas.lista_notas[0] = Double.parseDouble(campo_nota1.getText()); // obtiene la nota 1 del campo de texto y la convierte a double
        notas.lista_notas[1] = Double.parseDouble(campo_nota2.getText()); // obtiene la nota 2 del campo de texto y la convierte a double
        notas.lista_notas[2] = Double.parseDouble(campo_nota3.getText()); // obtiene la nota 3 del campo de texto y la convierte a double
        notas.lista_notas[3] = Double.parseDouble(campo_nota4.getText()); // obtiene la nota 4 del campo de texto y la convierte a double
        notas.lista_notas[4] = Double.parseDouble(campo_nota5.getText()); // obtiene la nota 5 del campo de texto y la convierte a double
        notas.calcular_promedio(); // calcula el promedio de las notas
        notas.calcular_desviacion(); // calcula la desviacion estandar de las notas
        notas.encontrar_mayor(); // encuentra la nota mayor
        notas.encontrar_menor(); // encuentra la nota menor
        label_promedio.setText("Promedio: " + String.valueOf(String.format("%.2f", notas.calcular_promedio()))); // muestra el promedio en el label
        label_desviacion.setText("Desviación estándar: " + String.valueOf(String.format("%.2f", notas.calcular_desviacion()))); // muestra la desviacion estandar en el label
        label_maxima.setText("Nota máxima: " + String.valueOf(String.format("%.2f", notas.encontrar_mayor()))); // muestra la nota mayor en el label    
        label_minima.setText("Nota mínima: " + String.valueOf(String.format("%.2f", notas.encontrar_menor()))); // muestra la nota menor en el label

    }//GEN-LAST:event_boton_calcularActionPerformed

    private void boton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarActionPerformed
        // TODO add your handling code here:
        campo_nota1.setText(""); // limpia el campo de texto de la nota 1
        campo_nota2.setText(""); // limpia el campo de texto de la nota 2
        campo_nota3.setText(""); // limpia el campo de texto de la nota 3
        campo_nota4.setText(""); // limpia el campo de texto de la nota 4
        campo_nota5.setText(""); // limpia el campo de texto de la nota 5
        label_promedio.setText("Promedio: "); // limpia el label del promedio
        label_desviacion.setText("Desviación estándar: "); // limpia el label de la desviacion estandar
        label_maxima.setText("Nota máxima: "); // limpia el label de la nota mayor
        label_minima.setText("Nota mínima: "); // limpia el label de la nota menor        
        
    }//GEN-LAST:event_boton_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_calcular;
    private javax.swing.JButton boton_limpiar;
    private javax.swing.JTextField campo_nota1;
    private javax.swing.JTextField campo_nota2;
    private javax.swing.JTextField campo_nota3;
    private javax.swing.JTextField campo_nota4;
    private javax.swing.JTextField campo_nota5;
    private javax.swing.JLabel label_desviacion;
    private javax.swing.JLabel label_maxima;
    private javax.swing.JLabel label_minima;
    private javax.swing.JLabel label_nota1;
    private javax.swing.JLabel label_nota2;
    private javax.swing.JLabel label_nota3;
    private javax.swing.JLabel label_nota4;
    private javax.swing.JLabel label_nota5;
    private javax.swing.JLabel label_promedio;
    // End of variables declaration//GEN-END:variables
}
